name: Keycloak Run Action Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test001:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Keycloak
        uses: ./
        with:
          keycloak_version: latest
      - name: KeyCloak is up
        run: bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8080/)" != "200" ]]; do sleep 5; done'
      - name: Tests (Install dependencies)
        working-directory: tests
        run: npm i
      - name: Tests (Execute command)
        working-directory: tests
        run: npm run test001
  test002:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Keycloak
        uses: ./
        with:
          keycloak_version: latest
          keycloak_http_port: 1234
      - name: KeyCloak is up
        run: bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:1234/)" != "200" ]]; do sleep 5; done'
      - name: Tests (Install dependencies)
        working-directory: tests
        run: npm i
      - name: Tests (Execute command)
        working-directory: tests
        run: npm run test002
  test003:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Keycloak
        uses: ./
        with:
          keycloak_version: latest
          keycloak_admin_user: my_admin
          keycloak_admin_pass: my_pass
      - name: KeyCloak is up
        run: bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8080/)" != "200" ]]; do sleep 5; done'
      - name: Tests (Install dependencies)
        working-directory: tests
        run: npm i
      - name: Tests (Execute command)
        working-directory: tests
        run: npm run test003
  test004:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Keycloak
        uses: ./
        with:
          keycloak_version: 19.0.3
      - name: KeyCloak is up
        run: bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8080/)" != "200" ]]; do sleep 5; done'
      - name: Tests (Install dependencies)
        working-directory: tests
        run: npm i
      - name: Tests (Execute command)
        working-directory: tests
        run: npm run test004
